    export interface Unit {
        _id: string;
        unitCategory: number;
        objectCategory: number;
        threatLvl: number;
        natoName: string;
        warbondCost: number;
        unitAttributes: string[];
    }
    export interface Weapon {
        _id: string;
        warbondCost: number;
        warbondKillMultiplier: number;
        isAntiRadiation: boolean;
        name: string;
        category: string;
        warheadName: string;
        displayName: string;
        weapon_name: string;
        guidanceType: number;
        missileCategory: number;
        warheadType: number;
    }
    // Generated by https://quicktype.io

export interface Events {
    _id:                 string;
    sessionName:         SessionName;
    eventCode:           EventCode;
    showInChart:         boolean;
    initiator?:          Initiator;
    weapon?:             EventWeapon;
    createdAt:           string;
    updatedAt:           string;
    __v:                 number;
    score?:              number;
    target?:             Initiator;
    killer?:             string;
    killerType?:         string;
    killerControlledBy?: string;
    victim?:             string;
    victimType?:         string;
    victimControlledBy?: VictimControlledBy;
    weapon_name?:        string;
    iucid?:              string;
    iName?:              string;
    displaySide?:        string;
    roleCode?:           string;
    msg?:                string;
}

export enum EventCode {
    D = "D",
    Kill = "KILL",
    ShootingStart = "SHOOTING_START",
    Shot = "SHOT",
}

export interface Initiator {
    category: number;
    groupId?: number;
    side:     number;
    type:     string;
    unitId:   number;
}

export enum SessionName {
    DrexMainServerDDCSModernSyria1673277253000 = "DrexMainServer_DDCS-Modern-Syria_1673277253000",
}

export enum VictimControlledBy {
    AI = "AI",
    Cahoot = "Cahoot",
    IDValkyr = "[.ID] Valkyr",
    SlDEWINDER = "SlDEWINDER",
}

export interface EventWeapon {
    category?:    number;
    displayName?: string;
    typeName?:    string;
    weapon_name:  string;
    impactPoint?: ImpactPoint;
    targetName?:  string;
}

export interface ImpactPoint {
    alt: number;
    lat: number;
    lon: number;
}
